# Generated by Django 5.2.7 on 2025-10-11 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0013_remove_question_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='likertquestion',
            options={},
        ),
        migrations.AlterModelOptions(
            name='multichoicequestion',
            options={},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={},
        ),
        migrations.RemoveField(
            model_name='question',
            name='polymorphic_ctype',
        ),
    ]
