# Generated by Django 5.2.6 on 2025-11-10 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0015_response_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='completed',
            field=models.BooleanField(default=True),
        ),
    ]
